/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DoctorRouteImport } from './routes/doctor'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as PatientRouteImport } from './routes/patient'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAccuracyRouteImport } from './routes/admin.accuracy'
import { Route as AdminPipelineRouteImport } from './routes/admin.pipeline'
import { Route as AdminRegulatoryRouteImport } from './routes/admin.regulatory'
import { Route as AdminRoadmapRouteImport } from './routes/admin.roadmap'
import { Route as DoctorIndexRouteImport } from './routes/doctor.index'
import { Route as DoctorDifferentialRouteImport } from './routes/doctor.differential'
import { Route as DoctorDossierRouteImport } from './routes/doctor.dossier'
import { Route as DoctorFeedbackRouteImport } from './routes/doctor.feedback'
import { Route as DoctorFlagsRouteImport } from './routes/doctor.flags'
import { Route as DoctorMonitoringRouteImport } from './routes/doctor.monitoring'
import { Route as DoctorSoapRouteImport } from './routes/doctor.soap'
import { Route as PatientIndexRouteImport } from './routes/patient.index'
import { Route as PatientCommunityRouteImport } from './routes/patient.community'
import { Route as PatientEnvironmentRouteImport } from './routes/patient.environment'
import { Route as PatientHandoffRouteImport } from './routes/patient.handoff'
import { Route as PatientHistoryRouteImport } from './routes/patient.history'
import { Route as PatientLabsRouteImport } from './routes/patient.labs'
import { Route as PatientMedicationsRouteImport } from './routes/patient.medications'
import { Route as PatientPhotoRouteImport } from './routes/patient.photo'
import { Route as PatientSymptomsRouteImport } from './routes/patient.symptoms'
import { Route as PatientTriageRouteImport } from './routes/patient.triage'
import { Route as PatientWellbeingRouteImport } from './routes/patient.wellbeing'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRoute = DoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientRoute = PatientRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccuracyRoute = AdminAccuracyRouteImport.update({
  id: '/accuracy',
  path: '/accuracy',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPipelineRoute = AdminPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRegulatoryRoute = AdminRegulatoryRouteImport.update({
  id: '/regulatory',
  path: '/regulatory',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRoadmapRoute = AdminRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => AdminRoute,
} as any)
const DoctorIndexRoute = DoctorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorDifferentialRoute = DoctorDifferentialRouteImport.update({
  id: '/differential',
  path: '/differential',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorDossierRoute = DoctorDossierRouteImport.update({
  id: '/dossier',
  path: '/dossier',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorFeedbackRoute = DoctorFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorFlagsRoute = DoctorFlagsRouteImport.update({
  id: '/flags',
  path: '/flags',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorMonitoringRoute = DoctorMonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorSoapRoute = DoctorSoapRouteImport.update({
  id: '/soap',
  path: '/soap',
  getParentRoute: () => DoctorRoute,
} as any)
const PatientIndexRoute = PatientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatientRoute,
} as any)
const PatientCommunityRoute = PatientCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => PatientRoute,
} as any)
const PatientEnvironmentRoute = PatientEnvironmentRouteImport.update({
  id: '/environment',
  path: '/environment',
  getParentRoute: () => PatientRoute,
} as any)
const PatientHandoffRoute = PatientHandoffRouteImport.update({
  id: '/handoff',
  path: '/handoff',
  getParentRoute: () => PatientRoute,
} as any)
const PatientHistoryRoute = PatientHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => PatientRoute,
} as any)
const PatientLabsRoute = PatientLabsRouteImport.update({
  id: '/labs',
  path: '/labs',
  getParentRoute: () => PatientRoute,
} as any)
const PatientMedicationsRoute = PatientMedicationsRouteImport.update({
  id: '/medications',
  path: '/medications',
  getParentRoute: () => PatientRoute,
} as any)
const PatientPhotoRoute = PatientPhotoRouteImport.update({
  id: '/photo',
  path: '/photo',
  getParentRoute: () => PatientRoute,
} as any)
const PatientSymptomsRoute = PatientSymptomsRouteImport.update({
  id: '/symptoms',
  path: '/symptoms',
  getParentRoute: () => PatientRoute,
} as any)
const PatientTriageRoute = PatientTriageRouteImport.update({
  id: '/triage',
  path: '/triage',
  getParentRoute: () => PatientRoute,
} as any)
const PatientWellbeingRoute = PatientWellbeingRouteImport.update({
  id: '/wellbeing',
  path: '/wellbeing',
  getParentRoute: () => PatientRoute,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/doctor': typeof DoctorRouteWithChildren
  '/mcp': typeof McpRoute
  '/patient': typeof PatientRouteWithChildren
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/accuracy': typeof AdminAccuracyRoute
  '/admin/pipeline': typeof AdminPipelineRoute
  '/admin/regulatory': typeof AdminRegulatoryRoute
  '/admin/roadmap': typeof AdminRoadmapRoute
  '/doctor/differential': typeof DoctorDifferentialRoute
  '/doctor/dossier': typeof DoctorDossierRoute
  '/doctor/feedback': typeof DoctorFeedbackRoute
  '/doctor/flags': typeof DoctorFlagsRoute
  '/doctor/monitoring': typeof DoctorMonitoringRoute
  '/doctor/soap': typeof DoctorSoapRoute
  '/patient/community': typeof PatientCommunityRoute
  '/patient/environment': typeof PatientEnvironmentRoute
  '/patient/handoff': typeof PatientHandoffRoute
  '/patient/history': typeof PatientHistoryRoute
  '/patient/labs': typeof PatientLabsRoute
  '/patient/medications': typeof PatientMedicationsRoute
  '/patient/photo': typeof PatientPhotoRoute
  '/patient/symptoms': typeof PatientSymptomsRoute
  '/patient/triage': typeof PatientTriageRoute
  '/patient/wellbeing': typeof PatientWellbeingRoute
  '/admin/': typeof AdminIndexRoute
  '/doctor/': typeof DoctorIndexRoute
  '/patient/': typeof PatientIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/accuracy': typeof AdminAccuracyRoute
  '/admin/pipeline': typeof AdminPipelineRoute
  '/admin/regulatory': typeof AdminRegulatoryRoute
  '/admin/roadmap': typeof AdminRoadmapRoute
  '/doctor/differential': typeof DoctorDifferentialRoute
  '/doctor/dossier': typeof DoctorDossierRoute
  '/doctor/feedback': typeof DoctorFeedbackRoute
  '/doctor/flags': typeof DoctorFlagsRoute
  '/doctor/monitoring': typeof DoctorMonitoringRoute
  '/doctor/soap': typeof DoctorSoapRoute
  '/patient/community': typeof PatientCommunityRoute
  '/patient/environment': typeof PatientEnvironmentRoute
  '/patient/handoff': typeof PatientHandoffRoute
  '/patient/history': typeof PatientHistoryRoute
  '/patient/labs': typeof PatientLabsRoute
  '/patient/medications': typeof PatientMedicationsRoute
  '/patient/photo': typeof PatientPhotoRoute
  '/patient/symptoms': typeof PatientSymptomsRoute
  '/patient/triage': typeof PatientTriageRoute
  '/patient/wellbeing': typeof PatientWellbeingRoute
  '/admin': typeof AdminIndexRoute
  '/doctor': typeof DoctorIndexRoute
  '/patient': typeof PatientIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/doctor': typeof DoctorRouteWithChildren
  '/mcp': typeof McpRoute
  '/patient': typeof PatientRouteWithChildren
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/accuracy': typeof AdminAccuracyRoute
  '/admin/pipeline': typeof AdminPipelineRoute
  '/admin/regulatory': typeof AdminRegulatoryRoute
  '/admin/roadmap': typeof AdminRoadmapRoute
  '/doctor/differential': typeof DoctorDifferentialRoute
  '/doctor/dossier': typeof DoctorDossierRoute
  '/doctor/feedback': typeof DoctorFeedbackRoute
  '/doctor/flags': typeof DoctorFlagsRoute
  '/doctor/monitoring': typeof DoctorMonitoringRoute
  '/doctor/soap': typeof DoctorSoapRoute
  '/patient/community': typeof PatientCommunityRoute
  '/patient/environment': typeof PatientEnvironmentRoute
  '/patient/handoff': typeof PatientHandoffRoute
  '/patient/history': typeof PatientHistoryRoute
  '/patient/labs': typeof PatientLabsRoute
  '/patient/medications': typeof PatientMedicationsRoute
  '/patient/photo': typeof PatientPhotoRoute
  '/patient/symptoms': typeof PatientSymptomsRoute
  '/patient/triage': typeof PatientTriageRoute
  '/patient/wellbeing': typeof PatientWellbeingRoute
  '/admin/': typeof AdminIndexRoute
  '/doctor/': typeof DoctorIndexRoute
  '/patient/': typeof PatientIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/doctor'
    | '/mcp'
    | '/patient'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/accuracy'
    | '/admin/pipeline'
    | '/admin/regulatory'
    | '/admin/roadmap'
    | '/doctor/differential'
    | '/doctor/dossier'
    | '/doctor/feedback'
    | '/doctor/flags'
    | '/doctor/monitoring'
    | '/doctor/soap'
    | '/patient/community'
    | '/patient/environment'
    | '/patient/handoff'
    | '/patient/history'
    | '/patient/labs'
    | '/patient/medications'
    | '/patient/photo'
    | '/patient/symptoms'
    | '/patient/triage'
    | '/patient/wellbeing'
    | '/admin/'
    | '/doctor/'
    | '/patient/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/accuracy'
    | '/admin/pipeline'
    | '/admin/regulatory'
    | '/admin/roadmap'
    | '/doctor/differential'
    | '/doctor/dossier'
    | '/doctor/feedback'
    | '/doctor/flags'
    | '/doctor/monitoring'
    | '/doctor/soap'
    | '/patient/community'
    | '/patient/environment'
    | '/patient/handoff'
    | '/patient/history'
    | '/patient/labs'
    | '/patient/medications'
    | '/patient/photo'
    | '/patient/symptoms'
    | '/patient/triage'
    | '/patient/wellbeing'
    | '/admin'
    | '/doctor'
    | '/patient'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/doctor'
    | '/mcp'
    | '/patient'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/accuracy'
    | '/admin/pipeline'
    | '/admin/regulatory'
    | '/admin/roadmap'
    | '/doctor/differential'
    | '/doctor/dossier'
    | '/doctor/feedback'
    | '/doctor/flags'
    | '/doctor/monitoring'
    | '/doctor/soap'
    | '/patient/community'
    | '/patient/environment'
    | '/patient/handoff'
    | '/patient/history'
    | '/patient/labs'
    | '/patient/medications'
    | '/patient/photo'
    | '/patient/symptoms'
    | '/patient/triage'
    | '/patient/wellbeing'
    | '/admin/'
    | '/doctor/'
    | '/patient/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  DoctorRoute: typeof DoctorRouteWithChildren
  McpRoute: typeof McpRoute
  PatientRoute: typeof PatientRouteWithChildren
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor': {
      id: '/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient': {
      id: '/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof PatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/accuracy': {
      id: '/admin/accuracy'
      path: '/accuracy'
      fullPath: '/admin/accuracy'
      preLoaderRoute: typeof AdminAccuracyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pipeline': {
      id: '/admin/pipeline'
      path: '/pipeline'
      fullPath: '/admin/pipeline'
      preLoaderRoute: typeof AdminPipelineRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/regulatory': {
      id: '/admin/regulatory'
      path: '/regulatory'
      fullPath: '/admin/regulatory'
      preLoaderRoute: typeof AdminRegulatoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roadmap': {
      id: '/admin/roadmap'
      path: '/roadmap'
      fullPath: '/admin/roadmap'
      preLoaderRoute: typeof AdminRoadmapRouteImport
      parentRoute: typeof AdminRoute
    }
    '/doctor/': {
      id: '/doctor/'
      path: '/'
      fullPath: '/doctor/'
      preLoaderRoute: typeof DoctorIndexRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/differential': {
      id: '/doctor/differential'
      path: '/differential'
      fullPath: '/doctor/differential'
      preLoaderRoute: typeof DoctorDifferentialRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/dossier': {
      id: '/doctor/dossier'
      path: '/dossier'
      fullPath: '/doctor/dossier'
      preLoaderRoute: typeof DoctorDossierRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/feedback': {
      id: '/doctor/feedback'
      path: '/feedback'
      fullPath: '/doctor/feedback'
      preLoaderRoute: typeof DoctorFeedbackRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/flags': {
      id: '/doctor/flags'
      path: '/flags'
      fullPath: '/doctor/flags'
      preLoaderRoute: typeof DoctorFlagsRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/monitoring': {
      id: '/doctor/monitoring'
      path: '/monitoring'
      fullPath: '/doctor/monitoring'
      preLoaderRoute: typeof DoctorMonitoringRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/soap': {
      id: '/doctor/soap'
      path: '/soap'
      fullPath: '/doctor/soap'
      preLoaderRoute: typeof DoctorSoapRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/patient/': {
      id: '/patient/'
      path: '/'
      fullPath: '/patient/'
      preLoaderRoute: typeof PatientIndexRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/community': {
      id: '/patient/community'
      path: '/community'
      fullPath: '/patient/community'
      preLoaderRoute: typeof PatientCommunityRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/environment': {
      id: '/patient/environment'
      path: '/environment'
      fullPath: '/patient/environment'
      preLoaderRoute: typeof PatientEnvironmentRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/handoff': {
      id: '/patient/handoff'
      path: '/handoff'
      fullPath: '/patient/handoff'
      preLoaderRoute: typeof PatientHandoffRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/history': {
      id: '/patient/history'
      path: '/history'
      fullPath: '/patient/history'
      preLoaderRoute: typeof PatientHistoryRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/labs': {
      id: '/patient/labs'
      path: '/labs'
      fullPath: '/patient/labs'
      preLoaderRoute: typeof PatientLabsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/medications': {
      id: '/patient/medications'
      path: '/medications'
      fullPath: '/patient/medications'
      preLoaderRoute: typeof PatientMedicationsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/photo': {
      id: '/patient/photo'
      path: '/photo'
      fullPath: '/patient/photo'
      preLoaderRoute: typeof PatientPhotoRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/symptoms': {
      id: '/patient/symptoms'
      path: '/symptoms'
      fullPath: '/patient/symptoms'
      preLoaderRoute: typeof PatientSymptomsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/triage': {
      id: '/patient/triage'
      path: '/triage'
      fullPath: '/patient/triage'
      preLoaderRoute: typeof PatientTriageRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/wellbeing': {
      id: '/patient/wellbeing'
      path: '/wellbeing'
      fullPath: '/patient/wellbeing'
      preLoaderRoute: typeof PatientWellbeingRouteImport
      parentRoute: typeof PatientRoute
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAccuracyRoute: typeof AdminAccuracyRoute
  AdminPipelineRoute: typeof AdminPipelineRoute
  AdminRegulatoryRoute: typeof AdminRegulatoryRoute
  AdminRoadmapRoute: typeof AdminRoadmapRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAccuracyRoute: AdminAccuracyRoute,
  AdminPipelineRoute: AdminPipelineRoute,
  AdminRegulatoryRoute: AdminRegulatoryRoute,
  AdminRoadmapRoute: AdminRoadmapRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DoctorRouteChildren {
  DoctorDifferentialRoute: typeof DoctorDifferentialRoute
  DoctorDossierRoute: typeof DoctorDossierRoute
  DoctorFeedbackRoute: typeof DoctorFeedbackRoute
  DoctorFlagsRoute: typeof DoctorFlagsRoute
  DoctorMonitoringRoute: typeof DoctorMonitoringRoute
  DoctorSoapRoute: typeof DoctorSoapRoute
  DoctorIndexRoute: typeof DoctorIndexRoute
}

const DoctorRouteChildren: DoctorRouteChildren = {
  DoctorDifferentialRoute: DoctorDifferentialRoute,
  DoctorDossierRoute: DoctorDossierRoute,
  DoctorFeedbackRoute: DoctorFeedbackRoute,
  DoctorFlagsRoute: DoctorFlagsRoute,
  DoctorMonitoringRoute: DoctorMonitoringRoute,
  DoctorSoapRoute: DoctorSoapRoute,
  DoctorIndexRoute: DoctorIndexRoute,
}

const DoctorRouteWithChildren =
  DoctorRoute._addFileChildren(DoctorRouteChildren)

interface PatientRouteChildren {
  PatientCommunityRoute: typeof PatientCommunityRoute
  PatientEnvironmentRoute: typeof PatientEnvironmentRoute
  PatientHandoffRoute: typeof PatientHandoffRoute
  PatientHistoryRoute: typeof PatientHistoryRoute
  PatientLabsRoute: typeof PatientLabsRoute
  PatientMedicationsRoute: typeof PatientMedicationsRoute
  PatientPhotoRoute: typeof PatientPhotoRoute
  PatientSymptomsRoute: typeof PatientSymptomsRoute
  PatientTriageRoute: typeof PatientTriageRoute
  PatientWellbeingRoute: typeof PatientWellbeingRoute
  PatientIndexRoute: typeof PatientIndexRoute
}

const PatientRouteChildren: PatientRouteChildren = {
  PatientCommunityRoute: PatientCommunityRoute,
  PatientEnvironmentRoute: PatientEnvironmentRoute,
  PatientHandoffRoute: PatientHandoffRoute,
  PatientHistoryRoute: PatientHistoryRoute,
  PatientLabsRoute: PatientLabsRoute,
  PatientMedicationsRoute: PatientMedicationsRoute,
  PatientPhotoRoute: PatientPhotoRoute,
  PatientSymptomsRoute: PatientSymptomsRoute,
  PatientTriageRoute: PatientTriageRoute,
  PatientWellbeingRoute: PatientWellbeingRoute,
  PatientIndexRoute: PatientIndexRoute,
}

const PatientRouteWithChildren =
  PatientRoute._addFileChildren(PatientRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  DoctorRoute: DoctorRouteWithChildren,
  McpRoute: McpRoute,
  PatientRoute: PatientRouteWithChildren,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
